### ISSUE TITLE
No service for type 'Mindscape.Raygun4Net.IRaygunUserProvider' has been registered in Mindscape.Raygun4Net.AspNetCore 11.2.0 in minimal api

### ISSUE THREAD

**Issue by StevenQuickGS1** [MindscapeHQ/raygun4net#554]
**Describe the bug**
Mindscape.Raygun4Net.AspNetCore 11.2.0 throws startup error "No service for type 'Mindscape.Raygun4Net.IRaygunUserProvider' has been registered." in .net 8 minimal api startup.

Previous versions did not have the issue.

**To Reproduce**
1. Create a new .net 8 minimal api, ie: dotnet new webapi -n raygun-example -f net8.0
2. dotnet add package Mindscape.Raygun4Net.AspNetCore
3. Add builder.Services.AddRaygun(builder.Configuration); and app.UseRaygun(); to program.cs
4. Try to run app, exception is thrown by app.Run()

**Expected behavior**
Exception is not thrown for missing dependency (IRaygunUserProvider) in minimal api

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser N/A
 - Version 11.2.0

**Additional context**
```
Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidOperationException: No service for type 'Mindscape.Raygun4Net.IRaygunUserProvider' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Mindscape.Raygun4Net.AspNetCore.ApplicationBuilderExtensions.<>c.<AddRaygun>b__2_0(IServiceProvider s) in C:\BuildAgent\work\97b7ce3b3781b48c\Mindscape.Raygun4Net.AspNetCore\ApplicationBuilderExtensions.cs:line 55
```

**Comment by phillip-haydon** [comment]
v11.2.1 has bee published. 

Sorry for the inconvenience. Let us know if you have any further issues. 

Thanks.
